# Homework 2

Dataset

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [9]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


Preparing the dataset

Use only the following columns:

'engine_displacement',

'horsepower',

'vehicle_weight',

'model_year',

'fuel_efficiency_mpg'

In [4]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print()

model_year
[2006 2008 1996 1989 1994]
50

origin
<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str
3

fuel_type
<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str
3

drivetrain
<StringArray>
['Front-wheel drive', 'Rear-wheel drive', 'All-wheel drive']
Length: 3, dtype: str
3

num_doors
[4 5 3 2]
4

engine_displacement
[2180 2390 2320 2130 2580]
127

num_cylinders
[6 7 5 8 4]
5

horsepower
[243. 272. 267. 258. 304.]
153

vehicle_weight
[3870 4210 4240 4490 4510]
176

acceleration
[ nan 17.3 18.7 17.5 18.8]
93

fuel_efficiency_mpg
[31.9 31.3 27.5 28.5 31. ]
188



EDA

Look at the fuel_efficiency_mpg variable. Does it have a long tail?

In [14]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [15]:
sns.histplot(df.msrp, bins=50)

AttributeError: 'DataFrame' object has no attribute 'msrp'

In [12]:
# ========================================================
# Q1 There's one column with missing values. What is it?
# 'engine_displacement'
# 'horsepower'
# 'vehicle_weight'
# 'model_year'

# ========================================================

missing_data = df.isnull().sum()
missing_cols = missing_data[missing_data > 0]

if not missing_cols.empty:
    print("Columns with missing valuess:")
    print(missing_cols)
else:
    print("No missing values available.")

Columns with missing valuess:
horsepower      877
acceleration    264
dtype: int64
